In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[0, 10],
              [30, 0.5]])
c = np.array([[2, 10],
              [30, 0.5]])

In [13]:
N = 5

In [17]:
lista = [1,2,3]

In [18]:
list(range(len(lista)))

[0, 1, 2]

In [15]:
a_start = np.random.uniform(0., 1./3, (N,N))
a_start

array([[0.2868158 , 0.15742731, 0.03077014, 0.29066189, 0.15031672],
       [0.33246627, 0.26073845, 0.18177789, 0.29639866, 0.31937233],
       [0.08192324, 0.13749837, 0.08756646, 0.02990284, 0.17102602],
       [0.05786461, 0.03237102, 0.13670876, 0.00670404, 0.32370164],
       [0.13100032, 0.07467518, 0.25730127, 0.16631869, 0.30438673]])

In [20]:
twodarray = np.random.rand(N, N)

In [21]:
twodarray

array([[0.74192209, 0.15748012, 0.63048165, 0.20545564, 0.00583985],
       [0.04904354, 0.04497741, 0.40219452, 0.34259192, 0.73615925],
       [0.41047695, 0.89172145, 0.59564962, 0.98378194, 0.61426813],
       [0.38582867, 0.03112   , 0.27203655, 0.40219424, 0.90569743],
       [0.07845214, 0.91354504, 0.3600088 , 0.78866275, 0.60526292]])

In [22]:
np.roll(twodarray, -1, axis=0)

array([[0.04904354, 0.04497741, 0.40219452, 0.34259192, 0.73615925],
       [0.41047695, 0.89172145, 0.59564962, 0.98378194, 0.61426813],
       [0.38582867, 0.03112   , 0.27203655, 0.40219424, 0.90569743],
       [0.07845214, 0.91354504, 0.3600088 , 0.78866275, 0.60526292],
       [0.74192209, 0.15748012, 0.63048165, 0.20545564, 0.00583985]])

In [23]:
twodarray

array([[0.74192209, 0.15748012, 0.63048165, 0.20545564, 0.00583985],
       [0.04904354, 0.04497741, 0.40219452, 0.34259192, 0.73615925],
       [0.41047695, 0.89172145, 0.59564962, 0.98378194, 0.61426813],
       [0.38582867, 0.03112   , 0.27203655, 0.40219424, 0.90569743],
       [0.07845214, 0.91354504, 0.3600088 , 0.78866275, 0.60526292]])